Dev 1.1.1
vegacloud/vega-metrics-agent pull request #12
Opened 2024-12-19 15:43 UTC by bclements

Refactor pod and agent metrics: rename collectors and remove security context metrics

- Updated collector names in the metrics agent to use singular form (e.g., "replicationcontroller" and "replicaset").
- Removed the security context metrics collection from the PodCollector and its associated struct in the metrics model, streamlining the metrics collected for pods.

Resolves:
#9 
#10

2024-12-19 17:38 UTC, ben-vega approved these changes

2025-01-02 16:47 UTC, Spencer-Vega commented on charts/vega-metrics-agent/Chart.yaml
> +version: 1.1.2
Would this need to be the same version as...

2025-01-02 16:47 UTC, Spencer-Vega commented on charts/vega-metrics-agent/values.yaml
> +  tag: 1.1.1
This?

2025-01-02 17:48 UTC, ben-vega commented on charts/vega-metrics-agent/values.yaml
> +  tag: 1.1.1
```suggestion
  tag: 1.1.2
```
per spencer's comment

2025-01-02 19:31 UTC, Spencer-Vega requested changes
Looks good other then my comments above

2025-01-03 16:42 UTC, Spencer-Vega approved these changes

2025-01-03 16:43 UTC, Spencer-G-Whit approved these changes

2025-01-03 16:43 UTC, merged